[package]
name = "bare-metal"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tock-registers = "0.10"
log = { version = "0.4", default-features = false }
riscv_plic = "0.2"
riscv = "0.16.1"

[[bin]]
name = "cvirtos"
path = "src/main.rs"
test = false

[profile.release]
panic = "abort"
opt-level = 1
lto = false
codegen-units = 1
debug = true
